fixing gpt4all.py to use get_model_from_type instead of model_type
This  is to fix the error :   File "\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\llms\gpt4all.py", line 156, in validate_environment
    values["backend"] = values["client"].model_type
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GPT4All' object has no attribute 'model_type'