Include API Error messages
To make this Error message from the API visible:
ValueError: Error raised by inference API: A valid user token is required

Without the change I get this Error, which is not very informative:
KeyError: 0
because generated_text[0] is inexistent.