fix: :bug: SQLAlchemy import error
During the import of langchain, SQLAlchemy was throeing an errror `ImportError: cannot import name 'Mapped' from 'sqlalchemy.orm'`. This is becaue the Mapped name was introduced in v1.4