VectorStore Typesense refactored example code and modified k value (#6159)
Changes done.
1. Example code in Typesense Class provided input embedding as
`embedding=embedding.embed_query` which throws an error as
`AttributeError: 'function' object has no attribute 'embed_query'`.
2. modified k values in vector similarity as Typesense by default
returns 10 results. So providing k =4 by default would make users think
about why the results are returned 10 instead of 4.


#### Who can review?

@jasonbosco @hwchase17 
 @dev2049

Co-authored-by: gaurav <gaurav.chauhan1@rksv.in>