A unit test calling a tool with no required parameters.
This generates a runtime error like

```
>>> t.run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: BaseTool.run() missing 1 required positional argument: 'tool_input'
```