Update openai.py
When using Elasticsearch Vectorstore, I encountered the following error due to a missing parameter. The issue has been resolved.
‵‵‵
InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>
```