Azure content filter error (#3861)
Hi all,

When trying to use GPT3.5 and GPT4 for a project I've been running into
a common non descriptive error
```
"...langchain/chat_models/openai.py", line 75, in _convert_dict_to_message
    return AIMessage(content=_dict["content"])
KeyError: 'content'
```

Just doing a little bit of debug shows this is due to Azure's content
filtering policies seen
[here](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/content-filter).

I've just added an error that highlights when these have been hit that
it is due to the policy, instead of failing without a descriptive error.
I couldn't find any other error types that have been setup in the repo
for content filters in specific so I used a value error but happy to add
a new type if that would be cleaner.