Fixes #8310 Fix maximum recursion depth exceeded error
ElasticsearchVectorStore.as_retriever() method is returning
RecursionError: maximum recursion depth exceeded because of incorrect field reference in
 embeddings() method