Include API Error messages in huggingface endpoint (#1183)
To make this Error message from the API visible:
ValueError: Error raised by inference API: A valid user token is
required

Without the change I get this Error, which is not very informative:
KeyError: 0
because generated_text[0] is inexistent.

The change I made in the code is similar to something already present in
huggingface_hub.py