Provided default values for tags and inheritable_tags args in BaseRunManager
To avoid the error message:

TypeError: BaseRunManager.__init__() missing 2 required keyword-only arguments: 'tags' and 'inheritable_tags'

when running AsyncCallbackManagerForChainRun (from langchain.callbacks.manager import AsyncCallbackManagerForChainRun), provided default values for tags and inheritable_tages of empty lists in manager.py BaseRunManager.