Fixes use of ImagePromptTemplate with Ollama
When using llava models / any ollama multimodal llms and passing images in the prompt as urls, langchain breaks with this error. 

```python
image_url_components = image_url.split(",")
                           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'split'
```

From the looks of it, there was bug where the condition did check for a `url` field in the variable but missed to actually assign it.

This PR fixes ImagePromptTemplate for Multimodal llms like llava when using Ollama specifically.